### ISSUE TITLE
Hello, how can I get the CGNA data set?

### ISSUE THREAD

**Issue by an123xinying** [SmithLiu95/Perceived-Emotions-Baseline#1]
Hello, I have a requirement for the CGNA dataset, can you tell me how to get it?

Thank you very much!

**Comment by SmithLiu95** [comment]
> Hello, I have a requirement for the CGNA dataset, can you tell me how to get it?
> 
> Thank you very much!

https://figshare.com/articles/CGnA10766_Dataset/5383105

**Comment by an123xinying** [comment]
谢谢！！！！！！！
